const RESOURCE_TYPE_DOCUMENT = 'Document'
const RESOURCE_TYPE_VIDEO = 'Video'
const RESOURCE_TYPE_E_TEXT_BOOK = 'eTextBook'
const RESOURCE_TYPE_WORKSHEET = 'Worksheet'

const resourceTypes = [RESOURCE_TYPE_DOCUMENT, RESOURCE_TYPE_VIDEO, RESOURCE_TYPE_E_TEXT_BOOK, RESOURCE_TYPE_WORKSHEET]

export default {
    RESOURCE_TYPE_DOCUMENT,
    RESOURCE_TYPE_VIDEO,
    RESOURCE_TYPE_E_TEXT_BOOK,
    RESOURCE_TYPE_WORKSHEET,
    resourceTypes
}